<?php

/**
 * BasePublicacionCoautor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $publicacion_id
 * @property integer $coautor_id
 * @property Autor $Autor
 * @property Publicacion $Publicacion
 * 
 * @method integer            getPublicacionId()  Returns the current record's "publicacion_id" value
 * @method integer            getCoautorId()      Returns the current record's "coautor_id" value
 * @method Autor              getAutor()          Returns the current record's "Autor" value
 * @method Publicacion        getPublicacion()    Returns the current record's "Publicacion" value
 * @method PublicacionCoautor setPublicacionId()  Sets the current record's "publicacion_id" value
 * @method PublicacionCoautor setCoautorId()      Sets the current record's "coautor_id" value
 * @method PublicacionCoautor setAutor()          Sets the current record's "Autor" value
 * @method PublicacionCoautor setPublicacion()    Sets the current record's "Publicacion" value
 * 
 * @package    pubudec
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublicacionCoautor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publicacion_coautor');
        $this->hasColumn('publicacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('coautor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Autor', array(
             'local' => 'coautor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Publicacion', array(
             'local' => 'publicacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}