<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/24 02:14:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=pubudec',
  'username' => 'admin',
  'password' => 'admin',
  'name' => 'doctrine',
)),);
