<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/08 22:18:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pubudec',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
