<?php
// auto-generated by sfViewConfigHandler
// date: 2012/01/24 02:14:45
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Pub - UdeC', false, false);
  $response->addMeta('description', 'Publicaciones - Universidad de Concepción', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('style.css', '', array ());
  $response->addStylesheet('fixed.css', '', array ());
  $response->addJavascript('excanvas.min.js', '', array ());
  $response->addJavascript('jquery-1.6.1.min.js', '', array ());
  $response->addJavascript('jquery.dataTables.min.js', '', array ());
  $response->addJavascript('jquery.labelify.js', '', array ());
  $response->addJavascript('jquery-ui-1.8.14.custom.min.js', '', array ());
  $response->addJavascript('iphone-style-checkboxes.js', '', array ());
  $response->addJavascript('jquery.ui.selectmenu.js', '', array ());
  $response->addJavascript('jquery.cleditor.min.js', '', array ());
  $response->addJavascript('jquery.flot.min.js', '', array ());
  $response->addJavascript('jquery.flot.pie.min.js', '', array ());
  $response->addJavascript('jquery.flot.stack.min.js', '', array ());
  $response->addJavascript('superfish.js', '', array ());
  $response->addJavascript('jquery.colorbox-min.js', '', array ());
  $response->addJavascript('fullcalendar.min.js', '', array ());
  $response->addJavascript('jquery.uploadify.v2.1.4.min.js', '', array ());
  $response->addJavascript('uploadify.js', '', array ());
  $response->addJavascript('jquery.tipsy.js', '', array ());
  $response->addJavascript('gcal.js', '', array ());
  $response->addJavascript('swfobject.js', '', array ());
  $response->addJavascript('examples.js', '', array ());
  $response->addJavascript('html5.js', '', array (  'condition' => 'IE 9',));
  $response->addJavascript('IE7.css', '', array (  'condition' => 'IE 7',));


