<?php

/**
 * AutorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object AutorTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Autor');
  }

  function getAutoresBySearch($q, $limit) {
    $q = Doctrine_Query::create()
            ->from('Autor a')
            ->Where("lower(a.nombre) like lower('%" . $q . "%')")
            ->orWhere("lower(a.apellido) like lower('%" . $q . "%')")
            ->addOrderBy('nombre')
            ->limit($limit);
    
    $autores = array();
    foreach ($q->execute() as $autor) {
      $autores[$autor->getId()] = (string) $autor;
    }
    return $autores;
  }

}