<?php

/**
 * PublicacionCoautorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicacionCoautorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicacionCoautorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicacionCoautor');
    }
}