<?php

/**
 * PublicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicacionTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PublicacionTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Publicacion');
  }

  static public $estados = array(
      'Aceptado' => 'Aceptado',
      'Publicado' => 'Publicado',
  );

  public function getEstados() {
    return self::$estados;
  }

}